#!/usr/bin/env bash
# Script prints the content of /etc/passwd but puts various information into a script.
passwd_file=/etc/passwd
while IFS=: read -r username password uid gid info home shell; do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info" 
done < passwd_file
