#!/usr/bin/env bash
#This will list the IPs and HTTP access codes of visitors but sort them by the number of occurences
log_file=apache-access.log
awk '{print $1, $9}' "$log_file"| sort | uniq -c | sort -nr
