#!/usr/bin/env bash
# This will use a combination of while, if, elif and else statements
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
	echo "Best School"	
		((i++)) 
	fi 
done
