#!/usr/bin/env bash
# This uses printf and hh:mm format to display time. It is a nested while loop. 
hour=0

while [ $hour -le 12 ] 
do 
	echo "Hour: $hour"

	minute=1
	while [ $minute -le 59 ] 
	do 
		echo $minute
		((minute++)) 
	done

	((hour++))
done
