#!/usr/bin/env bash
# Uses if/else to check 'school' file for various information
file=school

if [ -e "$file" ]; then 

	if [ -s "$file" ]; then
		echo "school file is not empty" 
	else
		echo "school file is empty" 
	fi 

	if [ -f "$file" ]; then
		echo "school file exists"
	else
		echo "school is not a regular file"
	fi
else
	echo "school file does not exist" 
fi
